# Generated by Django 3.2.9 on 2022-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_sale_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_statistics',
            name='revenue',
            field=models.FloatField(),
        ),
    ]
